// src/app/ai-discovery/page.js

'use client'

import Link from 'next/link'

const demos = [
  {
    id: 'manufacturing',
    name: 'PrecisionTech Manufacturing',
    industry: 'Industrial Manufacturing',
    revenue: '$250M',
    useCases: 7,
    roi: '111%',
    description: 'Equipment downtime, quality defects, supply chain visibility'
  },
  {
    id: 'retail',
    name: 'TechRetail Inc.',
    industry: 'E-commerce Retail',
    revenue: '$50M',
    useCases: 7,
    roi: 'TBD',
    description: 'Customer service costs, inventory management, cart abandonment'
  },
  {
    id: 'healthcare',
    name: 'Metro Health Systems',
    industry: 'Healthcare Provider',
    revenue: '$180M',
    useCases: 7,
    roi: 'TBD',
    description: 'Patient wait times, staff burnout, billing errors'
  },
  {
    id: 'fintech',
    name: 'Pinnacle Financial Group',
    industry: 'Financial Services',
    revenue: '$420M',
    useCases: 7,
    roi: 'TBD',
    description: 'Loan processing time, fraud detection, compliance costs'
  },
  {
    id: 'saas',
    name: 'CloudScale Analytics',
    industry: 'SaaS Technology',
    revenue: '$8M',
    useCases: 7,
    roi: 'TBD',
    description: 'Customer churn, lead qualification, support scaling'
  }
]

export default function DemoSelector() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-teal-900 to-slate-900 text-white py-12 px-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <Link href="/#apps" className="text-teal-400 hover:text-teal-300 mb-4 inline-block">
            ← Back to Home
          </Link>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Interactive Demo Analyses
          </h1>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Explore complete AI discovery analyses across 5 different industries. 
            Each analysis was generated by our 6-agent system.
          </p>
        </div>

        {/* Demo Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {demos.map((demo) => (
            <Link
              key={demo.id}
              href={`/ai-discovery/${demo.id}`}
              className="bg-slate-900/50 border border-teal-500/20 rounded-xl p-6 hover:border-teal-500 hover:shadow-xl hover:shadow-teal-500/10 transition-all group"
            >
              <h3 className="text-2xl font-bold mb-2 group-hover:text-teal-400 transition-colors">
                {demo.name}
              </h3>
              <div className="flex items-center gap-4 text-sm text-gray-400 mb-4">
                <span>{demo.industry}</span>
                <span>•</span>
                <span>{demo.revenue} revenue</span>
              </div>
              <p className="text-gray-300 mb-4 text-sm">
                {demo.description}
              </p>
              <div className="flex items-center justify-between pt-4 border-t border-gray-700">
                <div>
                  <div className="text-2xl font-bold text-teal-400">{demo.useCases}</div>
                  <div className="text-xs text-gray-400">Use Cases</div>
                </div>
                <div className="text-right">
                  <div className="text-2xl font-bold text-purple-400">{demo.roi}</div>
                  <div className="text-xs text-gray-400">Avg ROI</div>
                </div>
              </div>
              <div className="mt-4 text-teal-400 font-semibold group-hover:translate-x-2 transition-transform">
                View Analysis →
              </div>
            </Link>
          ))}
        </div>

        {/* CTA */}
        <div className="mt-16 text-center bg-slate-900/50 border border-teal-500/20 rounded-xl p-8">
          <h2 className="text-2xl font-bold mb-4">Want a Custom Analysis?</h2>
          <p className="text-gray-300 mb-6 max-w-2xl mx-auto">
            Get a comprehensive AI discovery analysis tailored to your tailored to your company&apos;s specific challenges and opportunities.
          </p>
          <Link 
            href="/#services"
            className="inline-block bg-teal-500 hover:bg-teal-600 text-white px-8 py-3 rounded-lg font-semibold transition-all"
          >
            View Services & Pricing
          </Link>
        </div>
      </div>
    </div>
  )
}